name: Build Brand Lexicon

on:
  push:
    paths:
      - 'catalogs/**'    # run ONLY when you drag/drop PDFs into catalogs/
  workflow_dispatch:      # allow manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract phrases and build lexicon
        run: |
          python scripts/extract_brand_phrases.py --input catalogs --output brand_lexicon.json

      - name: Commit & push if changed
        run: |
          if git diff --quiet brand_lexicon.json; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add brand_lexicon.json
            git commit -m "Update brand_lexicon.json [skip ci]"
            git push
          fi
